## Description of the functions
# makeCacheMatrix and cacheSolve are two functions working together to evaluate 
# a matrix, calculate the inverse, store the inverse in memory, evaluate if the 
# inverse of a matrix has already been calculated and in this case retrieve the 
# result from memory instead of recalculating the inverse. 

# makeCacheMatrix is a function that first of all generates a list to store the 
# original matrix and the inverse matrix once called by cacheSolve to work properly
# in conjuction with cacheSolve the returned list of makeCacheMatrix must be stored
# in a variable. 

makeCacheMatrix <- function(x = matrix()) {    # function of x in which x is by default a matrix
        m <- NULL                              # sets m to NULL in the function 
        set <- function(y) {                   # set is a function to reset x and m
                x <<- y                        # sets x to be y outside this function in the parent environment 
                m <<- NULL                     # sets m to NULL outside this function in the parent environment
        }
        get <- function() x                    # sets get to return x (the matrix), is called by cacheSolve in case there is no stored inverse matrix
        setinverse <- function(solve) m <<- solve # stores the inverse matrix in m and then in setinverse, which gets placed in the list
        getinverse <- function() m             # retrieves the inverse matrix (m) and can be called trough the list
        list(set = set, get = get,             # list that stores the matrix, inversed matrix etc
             setinverse = setinverse,
             getinverse = getinverse)        
}

#

cacheSolve <- function(x, ...) {              # function of x (still our matrix)
        m <- x$getinverse()                   # sets m in this function to be the results from getinverse (m set on level 1b)
        if(!is.null(m)) {                     # if there is an m defined in memory (m not NULL) this function
                message("getting cached data")# returns the message
                return(m)                     # and returns m (from the list generated by makeCacheMatrix)
        }                                     # otherwise
        data <- x$get()                       # data is defined as the input matrix used with makeCacheMatrix (here we call function 'get')
        m <- solve(data, ...)                 # define m as the inverse of the matrix (solve(matrix))
        x$setinverse(m)                       # place the inverse in the cache (in the list generated by makeCacheMatrix)
        m                                     # and return it at the same time
}